### ISSUE TITLE
Convert coordinates UCS to 2d

### ISSUE THREAD

**Issue by santiagocdo** [aleksandernitka/iohub_PsychoPy_EyeTracking#1]
Hello @aleksandernitka,

Hope you are well. I ran an experiment with Psychopy and ioHub, I extracted the .hdf5 using your tobii.extractor.R function. I can't find the 2d coordinate system that I will need to parse the ET raw data into Fixations and Saccades using a fixation detection algorithm (e.g. gazepath or saccades). I can't find an explanation for this either on the SDK or ET documentation.

My data looks like this: [ET_gitHub_help.xlsx](https://github.com/aleksandernitka/EyeTracking_Tobii_PsychoPy_IOHUB/files/3659034/ET_gitHub_help.xlsx); all I want to know is to get 2D X and Y gaze coordinates, preferably in pixels.

@grebdems @pedrotari7
I am wondering if this may be a problem with the Tobii SDK.

Regards,

Santiago C.

**Comment by aleksandernitka** [comment]
Hi @santiagocdo, apologies for the late reply, but I was occupied with PhD work and have not used github. Coordinates for x and y are stored as gaze_x and gaze_y and appear to be in order.

![gaze_x](https://user-images.githubusercontent.com/19268202/82182328-69032280-98e4-11ea-89c9-ba513882f51e.png)

![gaze_y](https://user-images.githubusercontent.com/19268202/82182345-728c8a80-98e4-11ea-8d93-a41af0db4d9e.png)

![gaze_xy](https://user-images.githubusercontent.com/19268202/82182358-77513e80-98e4-11ea-9a8f-ddcd4e090c86.png)

Please let me know if you're still having problems with this and I will look into this.

**Comment by santiagocdo** [comment]
Dear @aleksandernitka,
Thanks for your reply. Everything seems well. However, I was not sure in what unit gaze_x and gaze_y were, because the file includes also some z coordinates measurement. Now I know that is in pixels.
Thank you, and my best wishes.
